name: ai-expert-chatapp
services:
- name: backend
  source_dir: /backend
  github:
    repo: your-username/your-repo-name
    branch: main
  run_command: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /
  envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: PYTHONPATH
    scope: RUN_AND_BUILD_TIME
    value: /app

- name: frontend
  source_dir: /frontend
  github:
    repo: your-username/your-repo-name
    branch: main
  build_command: npm ci && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: REACT_APP_API_URL
    scope: BUILD_TIME
    value: ${backend.PUBLIC_URL} 